
server:
  port: 8080

  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true

spring:
  datasource:
#    ec2 db
    url: jdbc:mysql://blahblah-database.c0ojtysqxjes.ap-northeast-2.rds.amazonaws.com:3306/jaljara?useUnicode=true&characterEncoding=utf-8
    username: jaljara
    password: tXBUXtFK6zjrL3vPcyl8NoKgyTPjZ7Ss
    driver-class-name: com.mysql.cj.jdbc.Driver

#    local
#    url: jdbc:mysql://localhost:3306/jaljara?useUnicode=true&characterEncoding=utf-8
#    username: root
#    password: ssafy
#    driver-class-name: com.mysql.cj.jdbc.Driver

  output.ansi.enabled: always

  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: Asia/Seoul

logging.level:
  org.hibernate.SQL: debug
  #org.hibernate.type: trace